
import React from 'react';
import Layout from '../components/Layout';
import { ArrowUpRight } from 'lucide-react';

const PROJECTS = [
  {
    id: '1',
    title: 'Trivia Game',
    description: 'A multiplayer trivia game. Trivia questions generated by an AI agent.',
    tags: ['React', 'TypeScript', 'AI Agent', 'WebSockets'],
    link: 'https://pqrsgame.vercel.app',
    githubLink: 'https://github.com/OwenChen07/TriviaGame'
  },
  {
    id: '2',
    title: 'Machine Learning Chess Model',
    description: 'A machine learning model that uses a CNN to play chess',
    tags: ['ML', 'Python', 'PyTorch', 'Cloud Computing'],
    link: 'https://github.com/OwenChen07/ChessHacks'
  },
  {
    id: '3',
    title: 'DataSloth',
    description: 'A web application that finds datasets with strong correlation to input data',
    tags: ['Data Science', 'Python', 'Pandas', 'Scikit-Learn'],
    link: 'https://github.com/OwenChen07/DataSloth'
  },
  {
    id: '4',
    title: 'ConvoAI',
    description: 'An AI extension that displays real-time responses to spoken in video meetings',
    tags: ['LLMs', 'Python', 'OpenAI API', 'Flask'],
    link: 'https://github.com/LucasHJin/ConvoAI'
  },
  {
    id: '5',
    title: 'KCSSC Website',
    description: 'A dynamic website for a volunteer organization',
    tags: ['Web Dev', 'Typescript', 'React', 'PostgreSQL'],
    link: 'https://staging2.kcssc.org',
    githubLink: 'https://github.com/OwenChen07/kcssc-website-production'
  },
  {
    id: '6',
    title: 'Walky Talky',
    description: 'A long-distance remote controlled robot',
    tags: ['Robotics', 'Python', 'Raspberry Pi', 'SSH'],
    link: 'https://github.com/OwenChen07/WalkyTalky'
  },
  {
    id: '7',
    title: 'League of Legends Math Paper',
    description: 'An investigation into the math behind randomness in League of Legends',
    tags: ['Math', 'Statistics', 'Probability', 'NumPy'],
    link: '/Math%20IA.pdf'
  }
];

const Projects: React.FC = () => {
  return (
    <Layout>
      <div className="w-full flex flex-col items-center">
        <div className="pt-4 sm:pt-8 md:pt-12 mb-6 sm:mb-8 w-full max-w-2xl mx-auto px-4">
          <h1 className="text-4xl sm:text-5xl md:text-7xl font-bold mb-6 sm:mb-8 italic border-b border-darkOlive/20 dark:border-offWhite/20 pb-4 text-center">
            Projects
          </h1>
        </div>
        <div className="grid gap-4 sm:gap-6 max-w-5xl w-full px-4 sm:px-0">
        {PROJECTS.map((project, index) => (
          <div
            key={project.id}
            className="group border-b border-darkOlive/10 dark:border-offWhite/10 pb-4 sm:pb-6 hover:border-darkOlive dark:hover:border-offWhite transition-colors"
          >
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 sm:gap-6">
              <div className="space-y-3 sm:space-y-4">
                <div className="flex items-center gap-3 sm:gap-4">
                  <span className="text-xs opacity-40 font-mono">0{index + 1}</span>
                  <h3 className="text-2xl sm:text-3xl md:text-4xl font-semibold group-hover:italic transition-all">
                    {project.title}
                  </h3>
                </div>
                <p className="text-base sm:text-lg opacity-70 max-w-2xl font-light">
                  {project.description}
                </p>
                <div className="flex flex-wrap gap-2 sm:gap-4">
                  {project.tags.map(tag => (
                    <span key={tag} className="text-[10px] tracking-widest uppercase border border-darkOlive/20 dark:border-offWhite/20 px-2 py-1">
                      {tag}
                    </span>
                  ))}
                </div>
              </div>
              <div className="flex items-center gap-3 sm:gap-4 text-xs sm:text-sm font-medium uppercase tracking-widest opacity-0 group-hover:opacity-100 -translate-x-4 group-hover:translate-x-0 transition-all duration-300">
                <a
                  href={project.link}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 hover:opacity-70 transition-opacity"
                >
                  View Project
                  <ArrowUpRight size={16} className="sm:w-[18px] sm:h-[18px]" />
                </a>
                {project.githubLink && (
                  <a
                    href={project.githubLink}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-2 hover:opacity-70 transition-opacity"
                  >
                    GitHub
                    <ArrowUpRight size={16} className="sm:w-[18px] sm:h-[18px]" />
                  </a>
                )}
              </div>
            </div>
          </div>
        ))}
        </div>
      </div>
    </Layout>
  );
};

export default Projects;
